README.md

This adds a line to the readme to link to graphql-cli-codegen

Add graphql-cli-codegen in the Plugins section

---

src/cmds/get-schema.ts

This is to make errors like #23 easier to debug in the future if anyone else meets this

Only ignore schema-not-found errors

---

src/cmds/playground.ts

Fix linting issues

---

package.json
src/cmds/playground.ts
yarn.lock

This uses the new url handler of the Playground, if it is installed

Update to latest GraphQL Playground

---

package.json
src/cmds/create/boilerplates.ts
src/cmds/create/index.ts
yarn.lock

Fixes #75.
Tested with all existing boilerplates.

Revert unzip change

---

src/cmds/get-schema.ts

feat(get-schema): Allow insecure (self-signed) certificates

---

src/index.ts

Closes #19.
ExitCode 1 is now set on any error from any command.

fix: set exitCode on error

---

package.json
src/cmds/get-schema.ts

- Added JSON output (works with watch too)
- Added console output
- Refactored get-schema for better type safety
Related to #16.
Closes #13.

feat(get-schema): added JSON and console output options

---

.circleci/config.yml
.gitignore
package.json
yarn.lock

feat(release): include compiled binaries in release

---

package.json
yarn.lock

This affects the usage of the `graphql-cli` together with Graphcool projects

feat(playground): Update graphql-config-extension-graphcool.

---

package.json
src/cmds/get-schema.ts
yarn.lock

feat(get-schema): implement downloading from endpoint URL with headers

---

package.json
src/cmds/playground.ts
src/index.ts
yarn.lock

- updated `graphql-playground-middleware-express` (now passing in config)
- added `update-notifier`

Playground version

---

package.json
src/index.ts
yarn.lock

updated graphql-playground-middleware-express

fix(graphql-config): interpolate env vars of graphql-config

---

README.md

Just released this plugin.
In short, generates fragments for use in graphql queries.
https://www.apollographql.com/docs/angular/features/fragments.html

Added 'graphql generate-fragments' to Readme

---

src/cmds/query.ts

Issue: https://github.com/graphql-cli/graphql-cli/issues/201
Did some preliminary testing and this seems to work. Not very experienced in typescript so if there's any standard ways of doing things feel free to help me out!

Add variables option into query type.

---

package.json
yarn.lock

This reverts commit 48247d96aaeb9c39407b93383ef6574a4b04652e.

Revert "Update graphql-tools to 2.23.1"

---

package.json

Roll back adm-zip version to 0.4.7

---

src/cmds/get-schema.ts

1. Do not stop if existing schema is invalid
1. Do not save an invalid schema

fix: get-schema experience

---

src/index.ts

Fixes https://github.com/graphql-cli/graphql-cli/issues/326

fix: remove plugin exists warning

---

README.md

Add a logo to README

---

MIGRATION.md
README.md

Docs clarity.

---

.github/workflows/main.yml
.gitignore
CONTRIBUTING.md
MIGRATION.md
package.json
packages/commands/codegen/README.md
packages/commands/coverage/README.md
packages/commands/diff/README.md
packages/commands/generate/README.md
packages/commands/generate/package.json
packages/commands/init/README.md
packages/commands/serve/README.md
packages/commands/similar/README.md
packages/commands/validate/README.md
yarn.lock

Fix some issues related to graphback and perform package updates. 
Verify generate command (as part of this work)
Add some minimal information for contribution to simplify workflow.
CC @Urigo @ardatan

Minor fixes

---

packages/commands/init/src/index.ts

Example points to some legacy repo that was migrated.

chore: remove wtrocki example :D

---

packages/cli/src/cli.ts

chore: fixed minor typo

---

packages/commands/init/README.md
packages/commands/serve/README.md

- `GraphQL CLI serve command` -> `GraphQL CLI Init command`
- `GraphQL CLI Diff command` -> `GraphQL CLI Serve command`

[Docs]: fixed package names

---

README.md

Added a reference to `CONTRIBUTING.md` which one may miss out.

[Docs]: Added contributing guidelines section

---

README.md

Fixes invalid link to codegen plugin in README

docs(README): fix invalid link

---

packages/commands/init/src/common.ts
packages/commands/init/src/index.ts

Fixes https://github.com/Urigo/graphql-cli/issues/1421
/cc @wtrocki @craicoverflow will you have sometime to check this out?

feat(init): do not ask for project type when initialising project from scratch

---

README.md
packages/commands/generate/package.json
website/docs/command-generate.md

Update Graphback relevant documentation

docs(generate): update generate command docs

---

README.md
templates/fullstack/.graphqlrc.yml

The example graphql-config file using an older Graphback configuration.

docs: update README.md

---

website/docusaurus.config.js
website/package.json

Algolia Search configuration removal. Component moved to TGC.
https://github.com/the-guild-org/the-guild-components

[deploy_website] Algolia Config Removal
