Urigo/graphql-cli

src/cmds/get-schema.ts

- In non-watch mode, never catch errors.
- In watch mode, catch the whole `update` call and print the error, then retry after 10s. 
Fixes #21

Don't crash on errors in watch mode

---

README.md
package.json
src/cmds/index.ts
src/cmds/lint.ts
yarn.lock

Resolves Issue #14
Allow linting the graphql schema file via `graphql lint` command.

Schema linting

---

package.json
src/cmds/playground.ts
yarn.lock

Instead of sending all environment variables, with this PR, only the used ones are filtered.
Otherwise, the url limit of 2083 chars can be easily reached.

fix playground env var injection

---

package.json
src/cmds/create/index.ts
src/index.ts
yarn.lock

- Use `cross-spawn` to run yarn/npm (fixes #64)
- Use spinner for progress
- Use streaming unzip instead of temporary file
- Hide yarn/npm output (only show errors)

Windows fixes and other improvements to `create`

---

src/cmds/create/index.ts

- pass the `context` object to boilerplate install scripts
- add support for branches in shorthand (e.g. `owner/repo#branch`)
By passing the context, we're able to use the `prompt` in install commands, which will allow boilerplate creators to do more customized installs — for example, in a GrAMPS data source, this will allow setting global values such as the type prefix, data source namespace, and other values that are easy to update programmatically.
For testing, you can try this:
```bash
graphql create -b gramps-graphql/data-source-base#gql-cli-install data-source-test
```

feat: pass context to boilerplate install scripts

---

README.md
src/bin.ts

* The tool linked to `https://github.com/graphcool/graphql-cli`, which doesn't exist (though maybe it once did). Now it links to this repo.
* The link to the Graphcool CLI didn't work, so I changed it to one that does.
* I couldn't find a working link that describes the difference between graphql-cli and Graphcool CLI, so I took the answer [here](https://github.com/graphcool/framework/blob/master/docs/0.x/05-FAQ/06-Other.md)  and paraphrased, removing the link

Update some links and README

---

src/cmds/get-schema.ts

- fix: error on multiple `-p` (caused exception before)
- fix: error on multiple `-e` (caused exception before)
- feat: allow `-p *` and `-e *` to run get-schema on all projects and/or all endpoints. These arguments can be mix 'n match, so all of the following are valid:
* `graphql get-schema -p project1 -p project2 -e *`
* `graphql get-schema -p project1 -p project2 -e dev -e test` (only works if both projects have `dev` and `test` endpoints)
* `graphql get-schema -p * -e dev` (only works if all projects have a `dev` endpoint)
* `graphql get-schema -p * -e *`
* `graphql get-schema -p *` (only works if all projects have only one endpoint)
- feat: `--all` is shorthand for `-p * -e *`
- improved console output and error handling
Closes #54

feat(get-schema): allow all or multiple projects and endpoints

---

src/cmds/get-schema.ts

Running `graphql get-schema --json` without an output filename results in a cryptic error:
> path must be a string or Buffer
This updates the code to require `--output` if `--json` is given.

--json requires --output

---

src/cmds/get-schema.ts

This is meant to be a helper PR of https://github.com/prismagraphql/prisma/pull/2562
1. Failure of get-schema command must result in a non-zero exit status code and write to `stderr`

Fix hooks experience in CLI

---

src/cmds/get-schema.ts

Fixes #299
If both `--endpoint` and `--all` is specified, we ignore `--all` silently. This is because `--all` is activated by default.

fix(get-schema): if endpoint is provided, ignore all

---

src/cmds/get-schema.ts

If a project inside the config does not have endpoints, then all subsequent projects would be silently skipped because this `update()` function would return rather than continuing the loop to the next project.

Fix skipped endpoints bug in get-schema

---

packages/commands/generate/src/index.ts

Mapping GraphlQL-Config issue - it will return a valid object that represents the entire object under some circumstances. 
Even with valid config present. We should start with validating config to see if that is happening frequently.

fix: Add configuration validation for generate command

---

README.md

fix: Canary should be used instead of the version presented in the README

fix: Remove outdated info

---

packages/commands/init/src/index.ts

…plates
Migrating to graphql cli will be very simple by using graphql init. 
However, default values for model is not reflecting default one used in the template.
This simple change will reduce a lots of confusion in the community

fix: make default value compatible existing templates

---

renovate.json

Limit number of the PR created by renovate to just couple a day thanks to selective grouping to major/minor versions. Use pinned dependencies. Do not update the graphql package to the last when it is as transitive dependency.

chore: Improve renovate config

---

packages/commands/codegen/src/index.ts

fix: codegen command failed with the message
`codegenExtensionConfig.filter is not a function`
since its last change

Fix codegen config error

---

packages/cli/package.json

`resolve-from` is shipped with in-house type definitions.

chore(deps): remove stub type definition

---

templates/fullstack/server/tsconfig.json

Reverts a previous (unnecessary) change to the fullstack template's `noImplicitAny` tsconfig rule.

revert(tsconfig): set noImplicityAny rule to true

---

.gitignore
integration/package.json
integration/tests/workflow.ts
integration/tsconfig.json
package.json
templates/fullstack/client/src/generated-types.tsx
templates/fullstack/server/src/generated-types.ts
templates/fullstack/server/src/schema/generated.graphql

Current repo settings is allowing to introduce changes that do not work quite easly. 
Renovate merges changes automatically but there are no single test to check if anything in the repository will compile and produce result. 
This change tries to evaluate on existing template to see if codegen and generate works. We can follow with graphql-inspector commands easily to have full end to end test

fix: Add basic integration tests

---

packages/commands/init/src/index.ts

The idea in new graphback is to use plugins. With plugins asking some basic questions is more convoluted and hard. Before we came up with some basic use cases like - do you like subscriptions or datasync is easier to remove questions as they will not be effective or mapped to current implementation

Init cleanup

---

templates/fullstack/server/src/db.ts

Knex is being required in various places. When having different patch versions compilation will fail due to strange approach for typings in knex. Solution is to have flexible version of knex in the app level and never pass knex typed version to the core.
Additionally added error when someone will mess up with the config

fix: knex typings incompatibility

---

README.md

- codegen requires a `generates` field or else youre going to get a error like
```
yarn run v1.22.4
$ node_modules/graphql-cli/dist/bin.js codegen
✖ Parse configuration
→ Cannot convert undefined or null to object
Generate outputs
Cannot convert undefined or null to object
```

fix: update codegen fields

---

docs/MIGRATION.md

Links to GraphQL config docs 404'ed because they weren't correct. Have fixed it.

Update MIGRATION.md with correct doc links

---

.github/workflows/main.yml

Publish Canary workflow should not get triggered when a Release event is trigger. This should only happen on merge to master.
Error occurred in previous run: https://github.com/Urigo/graphql-cli/runs/1220494319?check_suite_focus=true 
This does not affect anything, the stable release was successful.

ci: do not trigger canary release along on release event
